version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  django:
    build:
      dockerfile: Dockerfile.django
      context: .
    # The server will run on localhost:8000
    # below was legacy project settings when the files were segregated
    # command: python manage.py runserver 0.0.0.0:8000 --settings=Chainlink.settings.docker
    command: bash -c "python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - webpack
  webpack:
    build:
      dockerfile: Dockerfile.webpack
      context: ./static/react
    working_dir: /code/static/react
    command: npm run dev
    volumes:
      - ./static/react:/code/static/react