FROM python:3.11.11-bookworm

# Specify directory for Django
WORKDIR /code

# Set Environment Variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH="/code" \
    DJANGO_SETTINGS_MODULE="Chainlink.settings"

# Install dependencies
COPY requirements.txt /code
RUN pip install -r requirements.txt