FROM python:3.11.11-bookworm

# Specify directory for Django
WORKDIR /code

# Set Environment Variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install dependencies
COPY requirements.txt /code
RUN pip install -r requirements.txt