# Generated by Django 3.2.19 on 2023-06-22 22:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chainlink',
            fields=[
                ('key', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('order', models.BigIntegerField(default=0)),
                ('public', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('key', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('h2', 'header2'), ('p', 'paragraph'), ('code', 'code'), ('h3', 'header3'), ('br', 'linebreak'), ('del', 'delimiter')], default='p', max_length=10)),
                ('order', models.BigIntegerField(default=0)),
                ('content', models.CharField(max_length=3000)),
                ('chainlink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patchwork.chainlink')),
            ],
        ),
        migrations.AddField(
            model_name='chainlink',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patchwork.doc'),
        ),
    ]
