# Generated by Django 3.2.22 on 2024-02-20 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chainlink',
            fields=[
                ('key', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=75)),
                ('order', models.BigIntegerField(default=0)),
                ('public', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('key', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Patchwork.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Patchwork.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('header', 'Header1'), ('chainlink', 'Chainlink'), ('paragraph', 'paragraph'), ('code', 'code'), ('header3', 'header3'), ('linebreak', 'linebreak'), ('article', 'Article'), ('text', 'Content')], default='paragraph', max_length=10)),
                ('order', models.BigIntegerField(default=0)),
                ('text', models.CharField(max_length=10000)),
                ('public', models.BooleanField(default=True)),
                ('chainlink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patchwork.chainlink')),
            ],
        ),
        migrations.AddField(
            model_name='chainlink',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patchwork.collection'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_page_url', models.CharField(default='null', max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
