# Generated by Django 3.2.19 on 2023-06-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patchwork', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chainlink',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='chainlink',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doc',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
    ]
