# Generated by Django 3.2.19 on 2023-06-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patchwork', '0004_content_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tag',
            field=models.CharField(choices=[('header2', 'header2'), ('paragraph', 'paragraph'), ('code', 'code'), ('header3', 'header3'), ('linebreak', 'linebreak'), ('delimiter', 'delimiter')], default='paragraph', max_length=10),
        ),
    ]
