# Generated by Django 3.2.20 on 2023-08-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patchwork', '0005_alter_content_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tag',
            field=models.CharField(choices=[('header1', 'header1'), ('header2', 'header2'), ('paragraph', 'paragraph'), ('code', 'code'), ('header3', 'header3'), ('linebreak', 'linebreak'), ('delimiter', 'delimiter')], default='paragraph', max_length=10),
        ),
    ]
